services:
  aura_grade:
    build:
      context: .
      dockerfile: Dockerfile
    image: stiwar1098/aura_grade
    container_name: aura_grade_app
    restart: always
    ports:
      - '${PORT}:${PORT}'

    environment:
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_USERNAME: ${DB_USERNAME}
      JWT_SECRET: ${JWT_SECRET}
      PORT: ${PORT}
      STATE: ${STATE}
      HOST_CLIENT: ${HOST_CLIENT}
