services:
  db:
    image: postgres:18.1-trixie
    restart: always # reiniciar el contenedor si se detiene
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    container_name: aura_grade_db
    volumes:
      - ./postgres:/var/lib/postgresql/data pg_upgrade --link
